### ISSUE TITLE
Str.graphemes are gone ...

### ISSUE THREAD

**Issue by normanjaeckel** [lukewilliamboswell/roc-json#10]
The new nightly build does not expose Str.graphemes anymore. So we get several `NOT EXPOSED` errors here.

```
── NOT EXPOSED in ....6.0/hJySbEhJV026DlVCHXGOZNOeoOl7468y9F9Buhj0J18/Core.roc ─

The Str module does not expose `graphemes`:

374│      Str.graphemes str
          ^^^^^^^^^^^^^

Did you mean one of these?

    Str.repeat
    Str.trim
    Str.reserve
    Str.capacity
```

**Comment by normanjaeckel** [comment]
Just adding the reference ...

https://github.com/roc-lang/roc/pull/6395

**Comment by Anton-4** [comment]
I'm working on a fix for this

**Comment by normanjaeckel** [comment]
@Anton-4 : You can take my code or parts of it or even reject my PR and find another solution. That's all ok for me. ;-)
