### ISSUE TITLE
Config options have no effect on object in array decoding

### ISSUE THREAD

**Issue by WhileTruu** [lukewilliamboswell/roc-json#13]
The following expectations fail when decoding an array of objects:

Field name mapping is not used
```
expect
    input = Str.toUtf8 "[{\"field_name\":1}]"

    decoder = jsonWithOptions { fieldNameMapping: SnakeCase }

    actual : DecodeResult (List { fieldName : U64 })
    actual = Decode.fromBytesPartial input decoder

    expected = Ok [{ fieldName: 1 }]

    actual.result == expected
```

Missing properties are skipped
```
expect
    input = Str.toUtf8 "[{\"extraField\":2,\"fieldName\":1}]"

    decoder = jsonWithOptions { skipMissingProperties: Bool.false }

    actual : DecodeResult (List { fieldName : U64 })
    actual = Decode.fromBytesPartial input decoder

    expected = Err TooShort

    actual.result == expected
```

**Comment by lukewilliamboswell** [comment]
I think I can see the issue [here](https://github.com/lukewilliamboswell/roc-json/blob/7628df21b2885e107fd6aac092d88c1220c9f499/package/Core.roc#L1204), it should take the arguments like [in here](https://github.com/lukewilliamboswell/roc-json/blob/7628df21b2885e107fd6aac092d88c1220c9f499/package/Core.roc#L1337C2-L1337C3) I think. 

I think I may not be able to look at this for a few days.
